### ISSUE TITLE
HTML kod strukturu sehfi

### ISSUE THREAD

**Issue by samirkarimov** [Ferid-Memmedli/PragmatechFoundationProject#2]
https://github.com/ferid221/PragmatechFoundationProject/blob/331612899aaf5c20ad5cb1cb6a24f7effb776662/index.html#L15

@ferid221  zehmet olmasa struktrudaki problemleri hellet

- [x] html section tagi oyren

- [x] sass import stilini oyren

**Comment by Ferid-Memmedli** [comment]
oldu))
