### ISSUE TITLE
Header margin problemi

### ISSUE THREAD

**Issue by samirkarimov** [Ferid-Memmedli/PragmatechFoundationProject#3]
- [x] #header hissəsində margin: 0 auto xüsusiyyətini əlavə et ki səhifə ortalansın
![Screenshot_3](https://user-images.githubusercontent.com/24611841/101158873-ed7d7e80-3645-11eb-81a9-c534718b6227.jpg)

**Comment by samirkarimov** [comment]
Eyni səkildə digər sectionlarin da sehife ortasina gelmesini temin etmek lazimdir

**Comment by Ferid-Memmedli** [comment]
Dediyiniz kimi eddim.amma ozumde ferqi gore bilmirem ekran olcusu kicikdi deye.Birdaha yoxluya bilersiz?
esas sectionlarin width i esasen px le verirler faizle?hansi daha duzgun olar.

**Comment by samirkarimov** [comment]
indi duzelib . grid sistemini responsive etməyi öyrəndikdən sonra o problem yəni olcu məsələsi həllediləcək

**Comment by Ferid-Memmedli** [comment]
o dersi sebrsizlikle gozduyurem)
