### ISSUE TITLE
Qeydlər

### ISSUE THREAD

**Issue by samirkarimov** [Ferid-Memmedli/PragmatechFoundationProject#4]
Layihə gedişatını bəyənirəm Fərid. Səliqə və bütövlük diqqətimi çəkdi.Bəzi məqamları qeyd edim onlara diqqət et bundan sonra

- Bir dəyər kod daxilində birdən çox dəfə istifadə olunubsa onu mütləq dəyişən halına gətirmək lazımdır. 
- Padding və margin kimi ölçüləndirmə məsələlərində öncədən sabit ölçülərə sahib dəyişənlər istifadə etsən işin sürətlənər (Nümunə p-1 :10px,p-2:20px və s )
- grid sass faylını məndən götürmüsən bunda problem yoxdur amma yaxçı olarki mənim yazdığım grid sistemini bir az özün inkişaf etdirib istifadə edəsən.Həmçinin mənim yazdığım digər kodları

Bu həftənin dəyərləndirməsi 9/10-dur

**Comment by Ferid-Memmedli** [comment]
1 ci ve 2 ci benddeki problemleri hell edmeye calisdim.
Grid le bagli tam arasdirma edmemisem deye girismemisdim.Olarida fixed edmeye calisacam

**Comment by samirkarimov** [comment]
Good cetinlik cekdiyin movzular hansilar olur adeten yeni vaxt alanlar hansilardirsa onu geyd elesen men ozumde geyd apararam

**Comment by Ferid-Memmedli** [comment]
Ilkin etapda strukturu quranda cetinlik cekirem neyi nece harda yerlesdirim deye bu mende vaxt biraz aparir ve birde responsive deil deye qicix oluram )))))ama umumen elede problem yasamiram.Ilkin olarak beynimde qurmaxa calisiram sistemi sef de olsa sora tokurem koda.Bir seyi unutdum demek olculendirmede cetinik cekrem

**Comment by samirkarimov** [comment]
olculendirme meselesini oturdmag ucun bizim yazdigimiz grid mentigini bir az nece deyeller hezm elesen o problemin hec galmayacaq
