### ISSUE TITLE
Mesafeler

### ISSUE THREAD

**Issue by samirkarimov** [Ferid-Memmedli/PragmatechFoundationProject#5]
https://github.com/ferid221/PragmatechFoundationProject/blob/d49aa760be6ece52706c0482be8dfa5430701374/sass/_veriables.scss#L12

Bu daha yaxsidi zamanla yene inkisaf etdirmek olar meselen

m-1 :10px (her terefden margin)
mt-1:10px (margin-top:10px)

bu geder detallandirmaga layihende ehtiyac varmi onu deyebilmerem amma fikir olsun deye dedim

**Comment by Ferid-Memmedli** [comment]
Fikir olaraq nezere aldim.Coxsagolun
