### ISSUE TITLE
Filter mesafe problemi

### ISSUE THREAD

**Issue by samirkarimov** [Ferid-Memmedli/PragmatechFoundationProject#7]
![filter](https://user-images.githubusercontent.com/24611841/102869415-00b98800-4455-11eb-9a53-faa6acdf1e91.jpg)
Filter prosesinde elementler arasinda mesafe problemi yaranir .. onu duzeltmek lazimdir

**Comment by Ferid-Memmedli** [comment]
Mellim bunu ozum bele edmisdim)sekiller ortalansin deye,3 sekildise 3 sekile uyxun bolunsun.2 dise 2 sekile ,1 sekldise ortada olsun.Yenede fix eddim.Artiq

**Comment by samirkarimov** [comment]
O formada edende duzgun dizaynda gorunmur ona gore dedim.. thanks
